apiVersion: v1
kind: Secret
metadata:
  name: taskflow-backend-secret
  namespace: dev
type: Opaque
stringData:
  MONGO_URI: "mongodb://cicia:h37O28fMdW1u5k49@db-mongodb-fra1-taskflow-ed090a8d.mongo.ondigitalocean.com:27017/taskflow?tls=true&authSource=admin&replicaSet=db-mongodb-fra1-taskflow"
  JWT_SECRET: "taskflow_secret_2024"