apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
  namespace: dev
  labels:
    app: taskflow-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
        - name: frontend
          image: sandra1002/taskflow-frontend:v13
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: taskflow-frontend-config
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
